### PR TITLE
Stale token refresh

### LINKED ISSUE #238: Handle stale tokens when page is left for over 10 minutes
### Description of the issue

If a page is left idle for 10 minutes, the access token will expire. If you then attempt to use any of the tables the fia-api requests will fail with an expired token. A refresh event is not triggered because there is no navigation.

We need to create a scigateway event in this scenario.

There are 2 obvious options:

1. Investigate if an interceptor can be attatched to all fetch requests to detect this behaviour and dispatch the refresh event before retrying the requests
2. If interceptors are not supported by `fetch` add axios and replace all fetch calls with axios and define the axios interceptor

Inspiration can be taken from here: https://github.com/ral-facilities/inventory-management-system/blob/a8fc73bd43bc762473e9c558d6fcd894c338d539/src/api/api.tsx#L9

### PR DESCRIPTION
**Pull request by keiranjprice101**
Closes #238 

- Creates single axios instance to be reused
- Remove the previous api urls spread around
- handles token expiry without page refresh
- removed some unused props

### CODE REVIEW

File: src/api.ts [hunk 1]
```diff
@@ -0,0 +1,65 @@
+import axios from 'axios';
+const isDev = process.env.REACT_APP_DEV_MODE === 'true';
```
Comment (Pasarus) [inline src/api.ts:2]:
```suggestion

const isDev = process.env.REACT_APP_DEV_MODE === 'true';
```
Can we add a line space here

**Review by Pasarus — CHANGES_REQUESTED** [review]
Just a couple bits:
- Can you pick one style of commenting in the api.ts file? either multiline // or /* */ ideally whatever is in other files.
- Also what is the difference between .ts and .tsx files? Should it be an api.tsx file?

Waiting for @Dagonite to see this

**Comment by keiranjprice101** [comment]
@Pasarus 
JSX and TSX is an extended syntax that allows html like markup. The api.ts has no JSX elements, so it's just TS

File: src/api.ts [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+//  all requests that failed due to an invalid token
+export const retryFailedAuthRequests = (): void => {
+  isFetchingAccessToken = false;
+  failedAuthRequestQueue.forEach((callback) => callback());
+  failedAuthRequestQueue = [];
+};
+
+// This should be called when SciGateway logs out as would occur if a token refresh fails
+// due to the refresh token being out of date - it rejects all active request promises that
+//  were awaiting a token refresh using the original error that occurred on the first attempt
```
Comment (Pasarus) [inline src/api.ts:20]:
```suggestion
// were awaiting a token refresh using the original error that occurred on the first attempt
```

File: src/api.ts [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+// We need to configure axios via interceptors because if the access token changes without a refresh the previous
+// token will still be used
+fiaApi.interceptors.request.use(async (config) => {
+  config.baseURL = process.env.REACT_APP_FIA_REST_API_URL;
+  config.headers['Authorization'] = `Bearer ${!isDev ? localStorage.getItem('scigateway:token') : ''}`;
+  return config;
+});
+
+// This should be called when SciGateway successfully refreshes the access token - it retries
+//    all requests that failed due to an invalid token
```
Comment (Pasarus) [inline src/api.ts:36]:
```suggestion
// all requests that failed due to an invalid token
```

**Review by Pasarus — CHANGES_REQUESTED** [review]
Just tidying this up a little bit :)

**Review by Pasarus — APPROVED** [review]

**Comment by Dagonite** [comment]
Pardon me, was being a bit silly about something regarding my understanding of Git.

I just want to test something with the config page before I approve and merge.

**Comment by Dagonite** [comment]
> * Also what is the difference between .ts and .tsx files? Should it be an api.tsx file?
> 
> Waiting for @Dagonite to see this

Like Kieran was saying, as there's no React components it doesn't need to be a `.tsx` file.
